# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Douyin_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 790)
        Form.setMinimumSize(QtCore.QSize(1000, 790))
        Form.setMaximumSize(QtCore.QSize(1000, 790))
        Form.setStyleSheet("QWidget#top_window {\n"
"border-radius:20px;\n"
"border: 1px solid rgba(243, 243, 243,0.5);\n"
"}")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.top_window = QtWidgets.QWidget(Form)
        self.top_window.setStyleSheet("background-color: rgb(34, 32, 32);")
        self.top_window.setObjectName("top_window")
        self.gridLayout = QtWidgets.QGridLayout(self.top_window)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.top_window)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_3.setStyleSheet("border-bottom: 1px solid grey;\n"
"margin:0 6px;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.head_logo = QtWidgets.QLabel(self.widget_3)
        self.head_logo.setMinimumSize(QtCore.QSize(180, 60))
        self.head_logo.setMaximumSize(QtCore.QSize(180, 60))
        self.head_logo.setStyleSheet("border-image: url(:/head/logo.png);")
        self.head_logo.setText("")
        self.head_logo.setObjectName("head_logo")
        self.horizontalLayout_6.addWidget(self.head_logo, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.parse_btn_2 = QtWidgets.QPushButton(self.widget_3)
        self.parse_btn_2.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.parse_btn_2.setFont(font)
        self.parse_btn_2.setStyleSheet("border:none;color:rgb(238, 238, 236);\n"
"")
        self.parse_btn_2.setObjectName("parse_btn_2")
        self.horizontalLayout_2.addWidget(self.parse_btn_2)
        self.parse_le = QtWidgets.QLineEdit(self.widget_3)
        self.parse_le.setMinimumSize(QtCore.QSize(600, 30))
        self.parse_le.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.parse_le.setFont(font)
        self.parse_le.setStyleSheet("    border:1px solid gray;\n"
"    height: 20px;\n"
"    border-radius:10px;\n"
"    padding:2px 4px;\n"
"    color:grey;")
        self.parse_le.setText("")
        self.parse_le.setObjectName("parse_le")
        self.horizontalLayout_2.addWidget(self.parse_le)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.setStretch(0, 3)
        self.horizontalLayout_6.setStretch(1, 10)
        self.horizontalLayout_6.setStretch(2, 1)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 2)
        self.widget_4 = QtWidgets.QWidget(self.top_window)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(238, 238, 236);")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setMinimumSize(QtCore.QSize(500, 0))
        self.widget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget.setStyleSheet("border: 1px solid grey;border-radius:5px;color: rgb(238, 238, 236);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.avatar_label = QtWidgets.QLabel(self.widget)
        self.avatar_label.setMinimumSize(QtCore.QSize(120, 120))
        self.avatar_label.setMaximumSize(QtCore.QSize(120, 120))
        self.avatar_label.setStyleSheet("border-radius: 60px;\n"
"border-image: url(:/douyin/douyin.png);")
        self.avatar_label.setText("")
        self.avatar_label.setObjectName("avatar_label")
        self.horizontalLayout_10.addWidget(self.avatar_label, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_4.addWidget(self.widget)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.desc_label = QtWidgets.QLabel(self.widget_4)
        self.desc_label.setMinimumSize(QtCore.QSize(500, 100))
        self.desc_label.setMaximumSize(QtCore.QSize(500, 16777215))
        self.desc_label.setStyleSheet("border: 1px solid grey;border-radius:5px;color: rgb(238, 238, 236);")
        self.desc_label.setText("")
        self.desc_label.setWordWrap(True)
        self.desc_label.setObjectName("desc_label")
        self.gridLayout_2.addWidget(self.desc_label, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.douyin_id_label = QtWidgets.QLabel(self.widget_4)
        self.douyin_id_label.setMinimumSize(QtCore.QSize(500, 0))
        self.douyin_id_label.setMaximumSize(QtCore.QSize(500, 50))
        self.douyin_id_label.setStyleSheet("border: 1px solid grey;border-radius:5px;color: rgb(238, 238, 236);")
        self.douyin_id_label.setText("")
        self.douyin_id_label.setObjectName("douyin_id_label")
        self.gridLayout_2.addWidget(self.douyin_id_label, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.author_name_label = QtWidgets.QLabel(self.widget_4)
        self.author_name_label.setMinimumSize(QtCore.QSize(500, 0))
        self.author_name_label.setMaximumSize(QtCore.QSize(500, 50))
        self.author_name_label.setStyleSheet("border: 1px solid grey;border-radius:5px;color: rgb(238, 238, 236);")
        self.author_name_label.setText("")
        self.author_name_label.setWordWrap(False)
        self.author_name_label.setObjectName("author_name_label")
        self.gridLayout_2.addWidget(self.author_name_label, 0, 1, 1, 1)
        self.create_time_label = QtWidgets.QLabel(self.widget_4)
        self.create_time_label.setMinimumSize(QtCore.QSize(500, 0))
        self.create_time_label.setMaximumSize(QtCore.QSize(500, 50))
        self.create_time_label.setStyleSheet("border: 1px solid grey;border-radius:5px;color: rgb(238, 238, 236);")
        self.create_time_label.setText("")
        self.create_time_label.setObjectName("create_time_label")
        self.gridLayout_2.addWidget(self.create_time_label, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.introduce_label = QtWidgets.QLabel(self.widget_4)
        self.introduce_label.setMinimumSize(QtCore.QSize(500, 100))
        self.introduce_label.setMaximumSize(QtCore.QSize(500, 16777215))
        self.introduce_label.setStyleSheet("border: 1px solid grey;border-radius:5px;color: rgb(238, 238, 236);")
        self.introduce_label.setText("")
        self.introduce_label.setWordWrap(True)
        self.introduce_label.setObjectName("introduce_label")
        self.gridLayout_2.addWidget(self.introduce_label, 2, 1, 1, 1)
        self.video_size_label = QtWidgets.QLabel(self.widget_4)
        self.video_size_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.video_size_label.setStyleSheet("border: 1px solid grey;border-radius:5px;color: rgb(238, 238, 236);")
        self.video_size_label.setText("")
        self.video_size_label.setObjectName("video_size_label")
        self.gridLayout_2.addWidget(self.video_size_label, 4, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.progressBar = QtWidgets.QProgressBar(self.widget_4)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(5000, 16777215))
        self.progressBar.setStyleSheet("background-color: grey;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_7.addWidget(self.progressBar)
        self.download_speed_label = QtWidgets.QLabel(self.widget_4)
        self.download_speed_label.setMinimumSize(QtCore.QSize(60, 0))
        self.download_speed_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.download_speed_label.setStyleSheet("color: rgb(238, 238, 236);")
        self.download_speed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.download_speed_label.setObjectName("download_speed_label")
        self.horizontalLayout_7.addWidget(self.download_speed_label)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.parse_btn = QtWidgets.QPushButton(self.widget_4)
        self.parse_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.parse_btn.setStyleSheet("QPushButton#parse_btn {\n"
"        border-radius: 8px;\n"
"        background-color: rgb(98, 169, 249);\n"
"}\n"
"QPushButton#parse_btn:hover {\n"
"        background-color: rgb(129, 190, 236);\n"
"}\n"
"QPushButton#parse_btn:pressed {\n"
"        background-color: rgb(45, 129, 186);\n"
"}")
        self.parse_btn.setObjectName("parse_btn")
        self.horizontalLayout_5.addWidget(self.parse_btn)
        self.clear_btn = QtWidgets.QPushButton(self.widget_4)
        self.clear_btn.setEnabled(False)
        self.clear_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.clear_btn.setStyleSheet("QPushButton#clear_btn {\n"
"        border-radius: 8px;\n"
"        background-color: rgb(98, 169, 249);\n"
"}\n"
"QPushButton#clear_btn:hover {\n"
"        background-color: rgb(129, 190, 236);\n"
"}\n"
"QPushButton#clear_btn:pressed {\n"
"        background-color: rgb(45, 129, 186);\n"
"}")
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_5.addWidget(self.clear_btn)
        self.play_btn = QtWidgets.QPushButton(self.widget_4)
        self.play_btn.setEnabled(False)
        self.play_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.play_btn.setStyleSheet("QPushButton#play_btn {\n"
"        border-radius: 8px;\n"
"        background-color: rgb(98, 169, 249);\n"
"}\n"
"QPushButton#play_btn:hover {\n"
"        background-color: rgb(129, 190, 236);\n"
"}\n"
"QPushButton#play_btn:pressed {\n"
"        background-color: rgb(45, 129, 186);\n"
"}")
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout_5.addWidget(self.play_btn)
        self.download_btn = QtWidgets.QPushButton(self.widget_4)
        self.download_btn.setEnabled(False)
        self.download_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.download_btn.setStyleSheet("QPushButton#download_btn {\n"
"        border-radius: 8px;\n"
"        background-color: rgb(98, 169, 249);\n"
"}\n"
"QPushButton#download_btn:hover {\n"
"        background-color: rgb(129, 190, 236);\n"
"}\n"
"QPushButton#download_btn:pressed {\n"
"        background-color: rgb(45, 129, 186);\n"
"}")
        self.download_btn.setObjectName("download_btn")
        self.horizontalLayout_5.addWidget(self.download_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.widget_4, 1, 0, 1, 1)
        self.v_widget = QtWidgets.QWidget(self.top_window)
        self.v_widget.setMinimumSize(QtCore.QSize(375, 0))
        self.v_widget.setMaximumSize(QtCore.QSize(375, 1000))
        self.v_widget.setStyleSheet("QWidget#v_widget{\n"
"background:#000;\n"
"border-radius:8px;}")
        self.v_widget.setObjectName("v_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.v_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 4)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.video_box = QtWidgets.QWidget(self.v_widget)
        self.video_box.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.video_box.setObjectName("video_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.video_box)
        self.verticalLayout_4.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addWidget(self.video_box)
        self.widget_2 = QtWidgets.QWidget(self.v_widget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.video_time = QtWidgets.QLabel(self.widget_2)
        self.video_time.setStyleSheet("background-color: rgba(238, 238, 236,0);color: rgb(186, 189, 182);")
        self.video_time.setObjectName("video_time")
        self.horizontalLayout_8.addWidget(self.video_time)
        self.play_sld = QtWidgets.QSlider(self.widget_2)
        self.play_sld.setMaximumSize(QtCore.QSize(16777215, 20))
        self.play_sld.setAcceptDrops(False)
        self.play_sld.setStyleSheet("background-color: rgba(255, 255, 255,0.1);\n"
"border:none;\n"
"")
        self.play_sld.setOrientation(QtCore.Qt.Horizontal)
        self.play_sld.setObjectName("play_sld")
        self.horizontalLayout_8.addWidget(self.play_sld)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.setStretch(0, 20)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout.addWidget(self.v_widget, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setRowStretch(0, 1)
        self.horizontalLayout_3.addWidget(self.top_window)

        self.retranslateUi(Form)
        self.parse_le.returnPressed.connect(Form.parse_video)
        self.play_btn.clicked.connect(Form.play)
        self.parse_btn.clicked.connect(Form.parse_video)
        self.clear_btn.clicked.connect(Form.clear_data)
        self.download_btn.clicked.connect(Form.download)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.parse_btn_2.setText(_translate("Form", "解析"))
        self.parse_le.setToolTip(_translate("Form", "ss"))
        self.parse_le.setPlaceholderText(_translate("Form", "请输入抖音分享链接..."))
        self.label.setText(_translate("Form", "作者头像："))
        self.label_3.setText(_translate("Form", "作者昵称："))
        self.label_4.setText(_translate("Form", "发布时间："))
        self.label_5.setText(_translate("Form", "作者抖音："))
        self.label_7.setText(_translate("Form", "作者简介："))
        self.label_8.setText(_translate("Form", "视频大小："))
        self.label_2.setText(_translate("Form", "作品描述："))
        self.label_6.setText(_translate("Form", "下载进度："))
        self.download_speed_label.setText(_translate("Form", "0M/s"))
        self.parse_btn.setText(_translate("Form", "解析"))
        self.clear_btn.setText(_translate("Form", "清除"))
        self.play_btn.setText(_translate("Form", "播放"))
        self.download_btn.setText(_translate("Form", "下载"))
        self.video_time.setText(_translate("Form", "00:00/00:00"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
